export const taskProgressRatio = [
    {
        id:1,
        userName: "Leslie Alexander",
        totalTask:"5",
        completedTask:"3",
        bgColor:"Purple-1300",
        textColor:"Purple-1200",
    },
    {
        id:2,
        userName: "Esther Howard",
        totalTask:"3",
        completedTask:"2",
        bgColor:"green-100",
        textColor:"green-300",
    },
    {
        id:3,
        userName: "Arlene McCoy",
        totalTask:"4",
        completedTask:"2",
        bgColor:"blue-100",
        textColor:"blue-300",
    },
    {
        id:4,
        userName: "Darlene Robertson",
        totalTask:"3",
        completedTask:"1",
        bgColor:"orange-200",
        textColor:"orange-300",
    },
    {
        id:5,
        userName: "Courtney Henry",
        totalTask:"3",
        completedTask:"3",
        bgColor:"green-100",
        textColor:"green-300",
    },
    {
        id:6,
        userName: "Jacob Jones",
        totalTask:"3",
        completedTask:"2",
        bgColor:"blue-100",
        textColor:"blue-300",
    },
]